# Generated by Django 5.1.1 on 2025-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
