# Generated by Django 5.1.1 on 2025-01-06 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='number',
            field=models.IntegerField(max_length=11, validators=[django.core.validators.MaxValueValidator(11)]),
        ),
    ]
